name: joshbeal
favicon: null
layout_spectrum: 0.21365
typography_spectrum: 0.27362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0708'
    - '#de1e43'
    - '#6c6656'
    - '#fefefe'
    - '#dfb89b'
  brandStrength: 0.7014815215952694
  lightness: 0.6771267955191433
  saturation: 0.7391260643489659
  rhythmicContrast: 0.5286046075634658
purpose: []
